language: node_js

sudo: false

env:
	global:
		- SAUCE_USERNAME="sebastiansandqvist"
		- SAUCE_ACCESS_KEY="d7e54d10-e63a-486d-a51c-be8099a1270c"

matrix:
	include:
		- node_js: "iojs-v3.0"
		- node_js: "iojs-v2.0"
		- node_js: "iojs-v1.0"
		- node_js: "0.12"
		- node_js: "0.10"
		env: BROWSER=1

addons:
  code_climate:
    repo_token: 6a96574ff5a9c05ad8206944d2f734da326380965fbbec6a757f82732ff6cf21
script: "npm run coverage"
after_script:
  - codeclimate-test-reporter < etc/lcov.info