sudo: false

language: node_js

env:
  global:
    - SAUCE_USERNAME='sebastiansandqvist'
    - SAUCE_ACCESS_KEY='d7e54d10-e63a-486d-a51c-be8099a1270c'

matrix:
  include:
    - node_js: 'iojs-v3.0'
      env: BROWSER=1